Zarmstrong patch 1
ruipin/fvtt-better-text-drawings pull request #7
Opened 2021-07-05 02:07 UTC by zarmstrong

this patch makes the window a little bit larger and sets the textarea to be 4 rows.  Additionally, upped the compatible version to 0.8.8.

![image](https://user-images.githubusercontent.com/565269/124408422-71463900-dd03-11eb-8544-a0b3cfb665b3.png)

2021-07-05 15:29 UTC, ruipin requested changes
Thanks for the pull request! The change is good, but I'm not very happy about the code style.

Added some comments in case you want to fix them yourself. Otherwise I can do them myself when I find some time.

2021-07-05 15:29 UTC, ruipin commented on better-text-drawings.js
> +		let parentWindow = textInput.parent().parent().parent().parent().parent();
Not a fan of this mass `parent()` chain. You probably should be using jQuery methods to search up for the application window.

2021-07-05 15:29 UTC, ruipin commented on better-text-drawings.js
> +        parentWindow.height(newwheight);
Identation needs fixing.

2021-07-05 15:29 UTC, ruipin commented on better-text-drawings.js
> +		console.log(parentWindow);
Debugging console messages should be removed

2021-07-05 15:47 UTC, ruipin commented
Just realised, changing the default window height should be done by wrapping DrawingConfig.defaultOptions.
There's even a comment in the code about this:

https://github.com/ruipin/fvtt-better-text-drawings/blob/4444c1515a2c44fa152bd5ebdb132f0c3b0216a0/better-text-drawings.js#L86-L87

2021-07-05 18:37 UTC, zarmstrong commented
I'm not super familiar with how libwrapper actually works, so I went with jquery. this is a lot cleaner than the previous way and could hopefully act as a stopgap until you have time to do it through libwrapper

2021-07-09 19:40 UTC, ruipin commented on better-text-drawings.js
> +		let parentWindow = textInput.parent().parent().parent().parent().parent();
I'll change this to libWrapper after merging.

2021-07-09 19:40 UTC, ruipin commented on better-text-drawings.js
> +        parentWindow.height(newwheight);
Looks fixed.

2021-07-09 19:40 UTC, ruipin commented on better-text-drawings.js
> +		console.log(parentWindow);
Now removed.

2021-07-09 19:41 UTC, ruipin approved these changes
I'll merge this and then change the resize to use libWrapper.

Thanks for the contribution!

2021-07-09 19:42 UTC, merged